name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: helaili/jekyll-action@2.4.0
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          target_branch: gh-pages